# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://thilinakavirathne_db_user:4THyqzTgK6w8Lbtn@staffleave.kchspdi.mongodb.net/leave_management?retryWrites=true&w=majority

# (optional, but clearer)
spring.data.mongodb.database=leave_management

# Helpful logs
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
logging.level.org.springframework.web=INFO